// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  menuLeft: string;
  menuRight: string;
  sqlEditorCompleted: string;
  sqlEditorCopy: string;
  sqlEditorDelete: string;
  sqlEditorFormat: string;
  sqlEditorMenu: string;
}
export const cssExports: CssExports;
export default cssExports;
